development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  pool: 75
  database: <%=ENV['PGDATABASE']%>
  username: <%=ENV['PGUSER']%>
  password: <%=ENV['PGPASSWORD']%>
  host:     localhost
  port:     <%=ENV['PGPORT']%>
  template: template0

test:
  adapter: sqlite3
  encoding: utf8
  reconnect: false
  pool: 15
  database: wanna_emails_test

production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  pool: 15
  database: <%=ENV['OPENSHIFT_APP_NAME']%>
  username: <%=ENV['OPENSHIFT_POSTGRESQL_DB_USERNAME']%>
  password: <%=ENV['OPENSHIFT_POSTGRESQL_DB_PASSWORD']%>
  host:     <%=ENV['OPENSHIFT_POSTGRESQL_DB_HOST']%>
  port:     <%=ENV['OPENSHIFT_POSTGRESQL_DB_PORT']%>
  template: template0