development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  pool: 75
  host: localhost
  port: 5432
  database: <%=ENV['DB_NAME']%>
  username: <%=ENV['DB_USERNAME']%>
  password: <%=ENV['DB_PASSWORD']%>
  template: template0

test:
  adapter: sqlite3
  encoding: utf8
  reconnect: false
  pool: 15
  database: wanna_emails_test

production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  pool: 15
  host:     <%=ENV['DB_HOST']%>
  port:     <%=ENV['DB_PORT']%>
  database: <%=ENV['DB_NAME']%>
  username: <%=ENV['DB_USERNAME']%>
  password: <%=ENV['DB_PASSWORD']%>
  template: template0
